version: '3.6'

services:
  app:
    image: blockchain_api:latest
    env_file:
      - config/docker.env
    ports:
      - "4001:4001"
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - config/docker.env
    restart: "always"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
