version: '3.5'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432
    env_file:
      - config/docker.env
  web:
    image: "blockchain_api:latest"
    ports:
      - "80:4001"
    volumes:
      - type: bind
        source: .
        target: /opt/app/blockchain_api
    env_file:
      - config/docker.env
    depends_on:
      - db
    command:
      - ./run.sh
